version: '3.8'

services:
  app:
    build: .
    container_name: product-catalog-app
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: product-catalog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_catalog
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
